#!/bin/bash
# use this script to run insys-onboarding on your local computer
# options 
# -d = DEV
# -p = PROD
# ./run -d

options_found=0
env=0
while getopts ":dp" opt; do
  case $opt in
    d)
        ((options_found++))
        ((env=1))
        ;;
    p)
        ((options_found++))
        ((env=2))
        ;;
    \?)
        echo "Invalid option: -$OPTARG.  Valid option is either -d or -p" >&2
        exit 1
        ;;
  esac  
done

# check if someone passed -d AND -p
if (($options_found != 1)); then
    echo "Invalid options passed.  Did you pass an environment option -d OR -p" >&2
    exit 1
fi

case $env in
    1)
        echo "Starting in DEV" >&2
        #======================= DEV ==============================
#         export PG_PRIMARY_CONNECT_STRING=postgres://username:password@dev-pgsql-service-1a/services?sslmode=disable
#         export PG_REPLICA_CONNECT_STRING=postgres://username:password@dev-pgsql-service-1a/services?sslmode=disable

        export PG_PRIMARY_CONNECT_STRING=postgresql://127.0.0.1:5432/insys_onboarding_local?sslmode=disable
        export PG_REPLICA_CONNECT_STRING=postgresql://127.0.0.1:5432/insys_onboarding_local?sslmode=disable

        export MAX_IDLE_CONNECTIONS=0
        export MAX_OPEN_CONNECTIONS=10
        export CONN_MAX_LIFETIME=15m
        export LOG_QUERIES=true

        export NSQ_CONCURRENT_HANDLERS=10
        export NSQ_MAX_IN_FLIGHT=10
        export NSQD_ADDR=127.0.0.1:4150
        export NSQ_LOOKUPD_ADDRS=127.0.0.1:4161
        export NSQ_LISTEN_CHANNEL=Onboarding

        export NSQ_CHILI_PIPER_SCHEDULE_EVENT_CREATED_TOPIC=ChiliPiperScheduleEventCreated
        export NSQ_PORTING_DATA_RECORD_CREATED_TOPIC=PortingDataCreated
        export NSQ_LOGIN_EVENT_CREATED_TOPIC=LoginEvent

        export AUTH_SERVICE_ADDRESS=dev-kube-load:30314
        export FEATURE_FLAGS_ADDRESS=dev-kube-load:30305
        export PORTING_DATA_GRPC_ADDRESS=dev-kube-load:30707

        export ZAPIER_URL=https://hooks.zapier.com/hooks/catch/883949/o246fjf
        ;;
    2)
        echo "Starting in PROD" >&2
        #======================= PROD ==============================
        export PG_PRIMARY_CONNECT_STRING=postgres://username:password@pgsql-service-1a/services?sslmode=disable
        export PG_REPLICA_CONNECT_STRING=postgres://username:password@pgsql-service-1a/services?sslmode=disable

        export MAX_IDLE_CONNECTIONS=0
        export MAX_OPEN_CONNECTIONS=15
        export CONN_MAX_LIFETIME=30m
        export LOG_QUERIES=false
        export DATA_LOCATION_ADDRESS=kube-load:30106

        export NSQ_CONCURRENT_HANDLERS=10
        export NSQ_MAX_IN_FLIGHT=10
        export NSQD_ADDR=127.0.0.1:4150
        export NSQ_LOOKUPD_ADDRS=127.0.0.1:4161
        export NSQ_LISTEN_CHANNEL=Onboarding

        export NSQ_CHILI_PIPER_SCHEDULE_EVENT_CREATED_TOPIC=ChiliPiperScheduleEventCreated
        export NSQ_PORTING_DATA_RECORD_CREATED_TOPIC=PortingDataCreated
        export NSQ_LOGIN_EVENT_CREATED_TOPIC=LoginEvent

        export AUTH_SERVICE_ADDRESS=kube-load:30314
        export FEATURE_FLAGS_ADDRESS=kube-load:30305
        export PORTING_DATA_GRPC_ADDRESS=kube-load:30707

        export ZAPIER_URL=https://hooks.zapier.com/hooks/catch/883949/o246fjf
        ;;
    *)
        echo "Unable to set runtime environment. Did you pass an environment option -d OR -p" >&2
        exit 1
        ;;
esac

go build -o insys-onboarding-service main.go  && ./insys-onboarding-service

